package tictactoe;

import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author merna
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setSize(1200, 700);
         intialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private String turn ="X";
    private int player1=0;
    private int player2=0;
   
    
  
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicTacToe");
        setBackground(new java.awt.Color(241, 240, 242));
        setForeground(new java.awt.Color(243, 12, 12));
        setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 100)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TicTacToe");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(3, 5, 1, 1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new java.awt.BorderLayout());

        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.BorderLayout());

        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new java.awt.BorderLayout());

        jButton4.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new java.awt.BorderLayout());

        jButton5.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        jButton5.setForeground(new java.awt.Color(247, 8, 8));
        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new java.awt.BorderLayout());

        jButton6.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new java.awt.BorderLayout());

        jButton7.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton7, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(new java.awt.BorderLayout());

        jButton8.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton8, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel10);

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Player1 score");
        jPanel11.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("0");
        jPanel12.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel12);

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel13.setLayout(new java.awt.BorderLayout());

        jButton11.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton11, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel13);

        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.setLayout(new java.awt.BorderLayout());

        jButton12.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton12, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel14);

        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.setLayout(new java.awt.BorderLayout());

        jButton13.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton13, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel15);

        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel16.setToolTipText("Player2 score");
        jPanel16.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jPanel16.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel6.setText("Player2 score");
        jPanel16.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel16);

        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("0");
        jPanel17.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel17);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       
            
        jButton3.setText(turn);
        setcolor(jButton3);
        whoseturn();
         whosewin();
        
        
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        reset();
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setText(turn);
         setcolor(jButton1);
        whoseturn();
         whosewin();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton2.setText(turn);
         setcolor(jButton2);
        whoseturn();
         whosewin();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jButton6.setText(turn);
         setcolor(jButton6);
        whoseturn();
         whosewin();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jButton7.setText(turn);
         setcolor(jButton7);
        whoseturn();
         whosewin();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jButton8.setText(turn);
         setcolor(jButton8);
        whoseturn();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jButton11.setText(turn);
         setcolor(jButton11);
        whoseturn();
         whosewin();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        jButton12.setText(turn);
         setcolor(jButton12);
        whoseturn();
         whosewin();
         
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jButton13.setText(turn);
        setcolor(jButton13);
        whoseturn();
        whosewin();
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
  
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

    private void intialize ()
    {
         jButton1.setText(null);
      jButton2.setText(null);
      jButton3.setText(null);
      jButton6.setText(null);
      jButton7.setText(null);
      jButton8.setText(null);
      jButton11.setText(null);
      jButton12.setText(null);
      jButton13.setText(null);
    }
      private void whoseturn()
    {
        if(turn.equals("X"))
            turn="O";
        else
            turn="X";
    }
    private void setcolor(javax.swing.JButton c)
    {
        if(turn.equals("X"))
        c.setForeground(Color.red);
        else
             c.setForeground(Color.blue);
    }
    private void whosewinner()
    {
        
    }
    private void whosewin(){
     
  String b1=jButton1.getText();
  String b2=jButton2.getText();
   String b3=jButton3.getText();
    String b4=jButton6.getText();
     String b5=jButton7.getText();
      String b6=jButton8.getText();
      String b7=jButton11.getText();
       String b8=jButton12.getText(); 
       String b9=jButton13.getText();
   if(b1=="X"&&b2=="X"&&b3=="X")
   {
      JOptionPane.showMessageDialog(null,  "player 1 win" ,"msg", JOptionPane.INFORMATION_MESSAGE);  
      player1++;
      intialize();
   }
 else  if(b1=="O"&&b2=="O"&&b3=="O")
   {
      JOptionPane.showMessageDialog(null,  "player 2 win" ,"msg", JOptionPane.INFORMATION_MESSAGE);  
      player2++;
      intialize();
   }
   else if(b4=="X"&&b5=="X"&&b6=="X")
   {
      JOptionPane.showMessageDialog(null,  "player 1 win" ,"msg", JOptionPane.INFORMATION_MESSAGE);  
      player1++;
      intialize();
   }
  else if(b4=="O"&&b5=="O"&&b6=="O")
   {
      JOptionPane.showMessageDialog(null,  "player 2 win" ,"msg", JOptionPane.INFORMATION_MESSAGE);  
      player2++;
      intialize();
   }
else if(b7=="X"&&b8=="X"&&b9=="X")
   {
      JOptionPane.showMessageDialog(null,  "player 1 win" ,"msg", JOptionPane.INFORMATION_MESSAGE);  
      player1++;
      intialize();
   }
 else  if(b7=="O"&&b8=="O"&&b9=="O")
   {
      JOptionPane.showMessageDialog(null,  "player 2 win" ,"msg", JOptionPane.INFORMATION_MESSAGE);  
      player2++;
      intialize();
   }
  else if(b1=="X"&&b4=="X"&&b7=="X")
   {
      JOptionPane.showMessageDialog(null,  "player 1 win" ,"msg", JOptionPane.INFORMATION_MESSAGE);  
      player1++;
      intialize();
   }
 else  if(b1=="O"&&b4=="O"&&b7=="O")
   {
      JOptionPane.showMessageDialog(null,  "player 2 win" ,"msg", JOptionPane.INFORMATION_MESSAGE);  
      player2++;
      intialize();
   }
 else  if(b2=="X"&&b5=="X"&&b8=="X")
   {
      JOptionPane.showMessageDialog(null,  "player 1 win" ,"msg", JOptionPane.INFORMATION_MESSAGE);  
      player1++;
      intialize();
   }
  else if(b3=="O"&&b5=="O"&&b8=="O")
   {
      JOptionPane.showMessageDialog(null,  "player 2 win" ,"msg", JOptionPane.INFORMATION_MESSAGE);  
      player2++;
      intialize();
   }
   else  if(b3=="X"&&b6=="X"&&b9=="X")
   {
      JOptionPane.showMessageDialog(null,  "player 1 win" ,"msg", JOptionPane.INFORMATION_MESSAGE);  
      player1++;
      intialize();
   }
   else if(b3=="O"&&b6=="O"&&b9=="O")
   {
      JOptionPane.showMessageDialog(null,  "player 2 win" ,"msg", JOptionPane.INFORMATION_MESSAGE);  
      player2++;
      intialize();
   }
  else if(b1=="X"&&b5=="X"&&b9=="X")
   {
      JOptionPane.showMessageDialog(null,  "player 1 win" ,"msg", JOptionPane.INFORMATION_MESSAGE);  
      player1++;
      intialize();
   }
  else if(b1=="O"&&b5=="O"&&b9=="O")
   {
      JOptionPane.showMessageDialog(null,  "player 2 win" ,"msg", JOptionPane.INFORMATION_MESSAGE);  
      player2++;
      intialize();
   }
 else  if(b3=="X"&&b5=="X"&&b7=="X")
   {
      JOptionPane.showMessageDialog(null,  "player 1 win" ,"msg", JOptionPane.INFORMATION_MESSAGE);  
      player1++;
      intialize();
   }
  else if(b3=="O"&&b5=="O"&&b7=="O")
   {
      JOptionPane.showMessageDialog(null,  "player 2 win" ,"msg", JOptionPane.INFORMATION_MESSAGE);  
      player2++;
      intialize();
   }
  else if(b1!=null&&b2!=null&&b3!=null&&b4!=null&&b5!=null&&b6!=null&&b7!=null&&b8!=null&&b9!=null)
   {
   JOptionPane.showMessageDialog(null,  "game tie" ,"msg", JOptionPane.INFORMATION_MESSAGE); 
   intialize();
   }
   jLabel3.setText(String.valueOf(player1));
   jLabel4.setText(String.valueOf(player2));
 }
  private void reset()
  {
      jButton1.setText(null);
      jButton2.setText(null);
      jButton3.setText(null);
      jButton6.setText(null);
      jButton7.setText(null);
      jButton8.setText(null);
      jButton11.setText(null);
      jButton12.setText(null);
      jButton13.setText(null);
      
  }
       
       
       
 }

